# if go build fails the image will return error
name: Test setup.sh and go build
# Controls when the action will run. 
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Make setup executable
        run: chmod +x ./setup.sh
      - name: Run setup script
        run: ./setup.sh
